services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        volumes:
            - ./:/var/www
            - ./.docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
    nginx:
        image: nginx
        tty: true
        ports:
            - '8989:80'
            - '443:443'
        env_file:
            - .env
        volumes:
            - ./:/var/www
            - ./.docker/nginx/:/etc/nginx/conf.d/
        networks:
            - app-network
    db:
        image: postgres:latest
        tty: true
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - app-network
    pgadmin:
        image: dpage/pgadmin4
        tty: true
        ports:
            - '5050:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: 'pgadmin@example.com'
            PGADMIN_DEFAULT_PASSWORD: 'admin'
        networks:
            - app-network
        depends_on:
            - db
    mailhog:
        image: mailhog/mailhog
        tty: true
        ports:
            - '8025:8025'
        networks:
            - app-network
    redis:
        image: redis:alpine
        tty: true
        ports:
            - '6379:6379'
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    postgres-data:
        driver: local
